Added GA import tab in no data screen
matomo-org/plugin-GoogleAnalyticsImporter pull request #423
Opened 2023-07-06 07:44 UTC by AltamashShaikh

### Description:

Added GA import tab in no data screen
Fixes: #PG-2903

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

2023-07-07 00:07 UTC, snake14 requested changes
Looks pretty good. I just left a couple comments.

2023-07-07 00:07 UTC, snake14 commented on lang/en.json
> +        "GAImportNoDataScreenStep04": "Follow the steps %1$sin this guide%2$s to download the OAuth credentials from your Google console.",
I think that this text is incorrect. It seems like step 4 should be about starting an import, because it's after the Authorize step. However, it's talking about downloading the OAuth credentials. It looks like it was copied from `GAImportNoDataScreenStep01` and not updated.
![image](https://github.com/matomo-org/plugin-GoogleAnalyticsImporter/assets/11394099/57b0144c-5ab9-42ae-bd44-f088b9737e3b)

2023-07-07 00:07 UTC, snake14 commented on vue/src/Configure/ConfigureConnection.vue
> +      {{ translate('GoogleAnalyticsImporter_Authorize') }}
Should this button and the text above reflect when the customer has already authorized, like maybe changing the text to re-authorize?

2023-07-07 00:07 UTC, snake14 commented on vue/src/Configure/ConfigureConnection.vue
> +  <li v-if="isNoDataPage" v-html="getAdvanceConnectStep01Text"></li>
Should this v-html attribute use `$sanitize`? If so, it looks like there are a several more below that probably need to as well.

2023-07-09 22:34 UTC, snake14 approved these changes
Looks good! I like that it now acknowledges when a config has been uploaded and when it has been authorized.

2023-07-09 22:34 UTC, snake14 commented on tests/UI/expected-ui-screenshots/EmptySite_GA_emptySiteDashboard.png
I was expecting the tracking code tab, but I guess we don't have much control over the fact that the builds show the Cloudflare tab instead.

2023-07-10 01:18 UTC, AltamashShaikh commented on tests/UI/expected-ui-screenshots/EmptySite_GA_emptySiteDashboard.png
@snake14 It requires core PR to be merged

2023-07-12 08:19 UTC, merged